#!/bin/bash
#
# Küsitakse  vanust
read -p "Sisesta oma vanus: " vanus
#
# Kontrollitakse,  kas sisestatud väärtus on number
if ! [[ "$vanus" =~ ^[0-9]+$ ]]; then
    echo "Viga"
    exit 1
fi
#
# Määratakse  vastav sõnum vastavalt vanusele
if ((vanus >= 0 && vanus <= 11)); then
    echo "Oled laps."
elif ((vanus >= 12 && vanus <= 18)); then
    echo "Oled nooruk."
elif ((vanus >= 19 && vanus <= 63)); then
    echo "Oled täiskasvanu."
else
    echo "Oled senjoor."
fi
