#!/bin/bash
#
# See skript välastab kasutajale kuupäeva ja aja
# Skript kasutab date käsku kuupäeva ja kellaaja kuvamiseks
#
# kuva tänane kuupäev
current_date=$(date "+%A, %B %d, %Y")
#
# kuva praegune kellaaeg
current_time=$(date "+%H:%M")
#
# kuva kalender
calendar=$(cal)
#
# Väljasta tulemused
echo "Today is $current_date"
echo "Time is $current_time"
echo ""
echo "$calendar"
