#!/bin/bash

echo "Sisesta ridade arv: "
read ridade_arv

echo "Sisesta tärnide arv reas: "
read tarnide_arv

for i in $(seq $ridade_arv)
do
    for j in $(seq $tarnide_arv)
    do
        echo -n "* "
    done
    echo
done
